### PR TITLE
Added an --xml-dir option to pbp-meta-gen

### PR DESCRIPTION
**Pull request by spacetimeengineer**
I have tested all scenarios I can think of. Linux, windows and all possible command configurations where --xml-dir is not specified and where it is. In all cases it passes the tests I imposed on it. If I move around the xml logs it works, if it cant find them it will tell you. As far as the abstract class is concerned, the xml-dir is now required but the scripts will provide the variable as the same as the audio directory unless the user specifies otherwise by --xml-dir.

### CODE REVIEW

**Comment by spacetimeengineer** [comment]
I forgot about the tests. Ill take care of those shortly.

**Comment by danellecline** [comment]
What a terrific contribution. The option and its behavior make good sense to me.
Many thanks @spacetimeengineer 💯

**Comment by spacetimeengineer** [comment]
Thanks Danelle, glad you like it. In the end I had to create a new abstract class specifically for SOUNDTRAP because I couldn't impose an xml-dir required or not on the other devices. Still working on fixing this last build error.

**Comment by spacetimeengineer** [comment]
Thanks Danelle!

**Pull request merged**
