### PR TITLE
Made pbp-hmb-gen Windows compatible

### PR DESCRIPTION
**Pull request by spacetimeengineer**
From the below command and with this branch I was able to generate a netCDF file with substantial data ~ 12.5MB although I have not plotted it yet. This fix was similar to the one I provided for the pbp-meta-gen. There was a runtime warning provided but it seems effectively inconsequential. -Michael

```
(mbari-pbp) C:\Users\michael.ryan\Desktop\SOUNDTRAP>pbp-hmb-gen --json-base-dir  C:\Users\michael.ryan\Desktop\SOUNDTRAP\PYPAM\JSON --audio-base-dir C:\Users\michael.ryan\Desktop\SOUNDTRAP --date 20220521 --output-dir C:\Users\michael.ryan\Desktop\SOUNDTRAP --global-attrs file:\\\C:\Users\michael.ryan\Desktop\SOUNDTRAP\globalAttributes_USTR01.yaml --variable-attrs file:\\\C:\Users\michael.ryan\Desktop\SOUNDTRAP\variableAttributes_USTR01.yaml --sensitivity-flat-value 176.2
C:\Users\michael.ryan\AppData\Local\anaconda3\envs\mbari-pbp\lib\site-packages\xarray\core\computation.py:761: RuntimeWarning: divide by zero encountered in log10
  result_data = func(*input_data)
```

### CODE REVIEW

**Comment by carueda** [comment]
Thanks @spacetimeengineer for your continued contributions!

https://github.com/mbari-org/pbp/actions/runs/10616911631/job/29428458628?pr=32

Can you please address the failed CI?

**Comment by spacetimeengineer** [comment]
Acknowledged.. Trying to find the problem.

**Comment by carueda** [comment]
Still failing

image

Please run `poetry run ruff format .` and then commit/push the format fix. Thanks!

**Review by carueda — APPROVED** [review]
I cannot perform any testing of this at the moment, but, per the conditioned variable updates, seems like it should not affect other OSs.

**Comment by carueda** [comment]
Thanks again.  I merged this knowing that adjustments are still needed (given that type checking got broken), which I'm doing now ...

In particular, I'm fixing this problem:
```
poetry run mypy .
pbp/process_helper.py:150: error: Value of type "str | None" is not indexable  [index]
```

**Comment by carueda** [comment]
Hi @spacetimeengineer

- https://github.com/mbari-org/pbp/commit/6989355816deb1e50d4533d8239b6acb3b7e8a99 fixes two issues in your changes.
- however, I then also did https://github.com/mbari-org/pbp/commit/a699c842a907524f6115d3be175ed228d677dc4b, which replaces `\` to `\\` for proper escaping of the backslash. This should be OK but please verify when you get a chance.

Just adding comments here in this PR, but feel free to create any new tickets if you note issues.

Thanks again.

**Pull request merged**
